### ISSUE TITLE
Email Tag System is Too Biased for it being used for Payment related emails

### ISSUE THREAD

**Issue by chriscct7** [awesomemotive/easy-digital-downloads#2151]
As part of the emails class rewrite we need to move email tags from being dependent on the email being related to purchases. Perhaps tags need to register a "context" or something. Because right now, if you're trying to use the email tags in a plugin that doesn't have to do with purchase emails, you cannot.

**Comment by danieliser** [comment]
I must say that I can see a use for tag usage outside of purchases. I did what pippin suggested, by faking it in the EDD Donations extension for the User Tax Receipts. Since its not based on a single purchase I had to fake it and load a single purchase from the user.

Can it be abstracted into a general function such as edd_tags in general which would accept text and an array of tags => values. Then the email tag function could simply be a wrapper with specific tags predefined?

**Comment by pippinsplugins** [comment]
That's what will need to happen I think.

**Comment by pippinsplugins** [comment]
Too close to 2.4 beta to get this in. For anyone that really wants this, I suggest putting a PR together to help move it along.

**Comment by cklosowski** [comment]
Closing out this issue, as we have plans to redo the entire email system. I want to focus on a singular issue related to email tagging and creation.
