### ISSUE TITLE
When searching payments by user email cancelled payments number doesn't update

### ISSUE THREAD

**Issue by chriscct7** [awesomemotive/easy-digital-downloads#4496]
If you search for payments by user email, the number of cancelled orders found does not update based on the search parameter

**Comment by pippinsplugins** [comment]
I don't think we should solve this bug, instead I think we should remove the cancelled status.

**Comment by cklosowski** [comment]
The only place I can even find EDD core using the 'cancelled' status is in the payment actions that get processed from the list table.

We do, however, use it in Stripe when pre-authorization is enabled, so that store owners can cancel a pre-auth'd payment record. I'm not sure we can just remove it, as it's not a 'failed' payment.

**Comment by robincornett** [comment]
I think we can close this as fixed in EDD 3.0, combined with https://github.com/awesomemotive/edd-stripe/issues/643 ... which makes sure that Stripe's custom statuses use the EDD counts.

**Comment by cklosowski** [comment]
This is fixed in EDD 3.0, I just confirmed.
