### ISSUE TITLE
Use batch processing API to build our earnings graphs

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#4678]
In order to improve the experience of sites with lots of sales data and make the line graphs more flexible for the data it can retrieve we should build the graphing system to use the AJAX Batch Processor. This will improve the overall performance of graphs with a large dataset, from the customer perspective as we won't be sitting there spinning (ending up with a possible timeout) but instead showing a nice system showing data collection process as we do so.

**Comment by pippinsplugins** [comment]
Yes! I think it's likely we will need to build a new version of the processing API instead of extending an existing one, but it'll be very, very similar.

This will let us build much, much better reporting :)

**Comment by sunnyratilal** [comment]
This in turn will also allow for our iOS app to be even faster

**Comment by pippinsplugins** [comment]
@sunnyratilal how so?

**Comment by sunnyratilal** [comment]
Allow users of the iOS app to view data from a date range really quickly and easily. It'd be great if we can update the REST API to leverage this batch processing API

**Comment by cklosowski** [comment]
@sunnyratilal currently the batch processing API relies on chaining AJAX requests from a front end, so we'd have to find another solution for the REST API.

**Comment by sunnyratilal** [comment]
Ahh ok - not a problem!  We’ll figure something out.


On 27 June 2016 at 18:51:57, Chris Klosowski (notifications@github.com)
wrote:

@sunnyratilal <https://github.com/sunnyratilal> currently the batch
processing API relies on chaining AJAX requests from a front end, so we'd
have to find another solution for the REST API.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4678#issuecomment-228805207>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABdHMnhCBH-WiW_QMO0RWdbfKT8xQEuXks5qP_-sgaJpZM4I01ti>
.

-- 
 

------------------------------

The contents of this email should be treated as confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you are not the named addressee you should not disseminate, distribute 
or copy this e-mail without express permission from Sunny Ratilal. Please 
notify the sender, Sunny Ratilal, immediately by e-mail if you have 
received this e-mail by mistake and delete this e-mail from your system.

**Comment by pippinsplugins** [comment]
This is going to have to move to 2.8.

**Comment by JJJ** [comment]
For huge datasets, some kind of batch processor will still be required.

The custom database tables being introduced in the 3.0 release cycle will alleviate a lot of the current pains, but as stores age and acquire more sales, batching the results of frequently ran reports will be a useful feature to have.

Let's move this to 3.1, so we can get back-compat with the new tables in first, see how much they help, and revisit.

**Comment by cklosowski** [comment]
This is no longer necessary with 3.0...closing.
