### ISSUE TITLE
New settings look and navigability enhancement

### ISSUE THREAD

**Issue by rubengc** [awesomemotive/easy-digital-downloads#5705]
Some versions ago EDD publish a new design for customer screen, this design could be appicable for the settings page too

Also, as an enhancement of navigability you could add links of each tab sections (with the ability to toggle them) to allow access, for example, directly to Misc -> Terms of Agreement or any section you want

New settings navigation concept:
![test](https://cloud.githubusercontent.com/assets/5462480/25662328/6eae6848-3014-11e7-83a5-d513dc7313aa.PNG)

**Comment by cklosowski** [comment]
I think I like this idea...but I don't want to peg it to a milestone yet. I'm going to leave it as a `question` label. I have some concerns on the usability being that we'd have to expandable menus (WP Core, and then EDD's) right next to each other, as well as how it will break down on mobile since again, we'd have two sidebar menus loading with far more complex structure and logic than the customer cards do.

I'm not saying we can't do it, but I'd like to see it fully fleshed out and functional and used on many different sized screens before we set it for a milestone and adapt it. We modeled our subsections based off how WooCommerce did theirs because it held a pretty common structure for the way users interact with their ecommerce plugins, which is nice because it offers a similar layout than they are accustomed to when/if they move from WooCommerce to EDD.

**Comment by JJJ** [comment]
I've tweaked some mark-up and CSS for EDD3.0. It's not a complete rewrite or redesign like was proposed originally, but I _did_ want to clean up a bunch of Settings specific inconsistencies and discoverability issues.

<img width="1162" alt="screen shot 2018-05-08 at 12 19 35 pm" src="https://user-images.githubusercontent.com/88951/39772314-94904a3a-52ba-11e8-9857-0ad9d63d7682.png">

Here's a high-level overview of things I've tweaked:

* Our `subsubsub` navigation is chunkier, making it easier to discover and creating a natural hierarchy
* Chosen now uses styling much more closer to WordPress core
* Setting labels in the `th` now link to the input
* Checkboxes and radio buttons are now wrapped in a `div` to avoid them running into each other
* All `header` objects use `h3` (some did, some didn't)
* I rearranged one or two settings to keep navigation consistent across all tabs
* I updated some strings to improve spelling & grammar

I went rogue this weekend and just pushed these changes to the `release/3.0` branch. Sorry for not sending in PRs, but:

* none of these changes are huge
* all of them together makes Settings pretty significantly better
* asking for forgiveness instead of permission? ¯\_(ツ)_/¯

**Comment by pippinsplugins** [comment]
I like the look of this! Could you go ahead and post screenshots of the other tabs?

>>>I went rogue this weekend and just pushed these changes to the release/3.0 branch.

All fair points but please always use issue branches. Security and hotfixes should be the only exception to that practice :)

**Comment by JJJ** [comment]
<img width="1002" alt="screen shot 2018-05-08 at 12 47 10 pm" src="https://user-images.githubusercontent.com/88951/39773698-70845cc2-52be-11e8-82a3-97f9787db755.png">
<img width="1000" alt="screen shot 2018-05-08 at 12 47 23 pm" src="https://user-images.githubusercontent.com/88951/39773699-70963ee2-52be-11e8-8ab5-7f0d333ce8a2.png">
<img width="1001" alt="screen shot 2018-05-08 at 12 47 35 pm" src="https://user-images.githubusercontent.com/88951/39773701-70a4c9e4-52be-11e8-8bdd-07efdf679ed5.png">
<img width="1001" alt="screen shot 2018-05-08 at 12 47 51 pm" src="https://user-images.githubusercontent.com/88951/39773702-70b623b0-52be-11e8-95ad-41093db6b831.png">
<img width="1000" alt="screen shot 2018-05-08 at 12 48 02 pm" src="https://user-images.githubusercontent.com/88951/39773703-70c4c668-52be-11e8-8dc9-5362111deeb0.png">
<img width="1001" alt="screen shot 2018-05-08 at 12 48 16 pm" src="https://user-images.githubusercontent.com/88951/39773704-70d54f38-52be-11e8-9945-f61bc2cccf08.png">
<img width="1002" alt="screen shot 2018-05-08 at 12 48 27 pm" src="https://user-images.githubusercontent.com/88951/39773705-70e5caa2-52be-11e8-80a9-516ddf2a93ae.png">
<img width="1001" alt="screen shot 2018-05-08 at 12 48 39 pm" src="https://user-images.githubusercontent.com/88951/39773706-70f50d78-52be-11e8-9fe6-d27ecdbde02b.png">
<img width="999" alt="screen shot 2018-05-08 at 12 48 52 pm" src="https://user-images.githubusercontent.com/88951/39773707-7105ef08-52be-11e8-9ac8-b2d8e80ef957.png">
<img width="1001" alt="screen shot 2018-05-08 at 12 49 07 pm" src="https://user-images.githubusercontent.com/88951/39773708-71164e20-52be-11e8-8597-2e4f39446e76.png">
<img width="999" alt="screen shot 2018-05-08 at 12 49 22 pm" src="https://user-images.githubusercontent.com/88951/39773709-71283f9a-52be-11e8-914f-c8e7ab7ee85a.png">
<img width="999" alt="screen shot 2018-05-08 at 12 49 37 pm" src="https://user-images.githubusercontent.com/88951/39773710-713a63a0-52be-11e8-9fbb-f6b889b72eb4.png">
<img width="1000" alt="screen shot 2018-05-08 at 12 49 51 pm" src="https://user-images.githubusercontent.com/88951/39773711-714b58d6-52be-11e8-8475-c34608150a7c.png">
<img width="1001" alt="screen shot 2018-05-08 at 12 50 02 pm" src="https://user-images.githubusercontent.com/88951/39773712-715a8a5e-52be-11e8-9e30-d08f8750b406.png">
<img width="1001" alt="screen shot 2018-05-08 at 12 50 15 pm" src="https://user-images.githubusercontent.com/88951/39773713-716a1334-52be-11e8-8228-9f437a82a9c3.png">

**Comment by cklosowski** [comment]
At this time we're not looking to shift the overall design of the settings UI. The work done in 3.0 is a great step forward and we've started to collapse a number of the additional tabs that get add into existing EDD settings areas to improve discoverability.

When it's time for a settings design redesign, we'll do a full UI/UX review and work with our designer to move forward.
