### ISSUE TITLE
Don't assume wp-admin

### ISSUE THREAD

**Issue by brashrebel** [awesomemotive/easy-digital-downloads#6370]
Some users rewrite the URL for the site admin so wp-admin no longer works. Can we support these configurations by dynamically obtaining and using the replacement directory OR by making a filter which can be used to swap the value throughout our codebase?

A customer is experiencing now one symptom because of this: Ajax isn't working in some cases. That's because right [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-session.php#L364) we're statically defining the path. They suggested changing that line to `if( is_admin() && ! (defined('DOING_AJAX') && DOING_AJAX) )...` which might be fine, but since there are a couple dozen other occurrences of `wp-admin` in EDD, perhaps a more comprehensive solution makes sense.

**Comment by cklosowski** [comment]
I think I'd be ok with this, but we should not use the constants. As a note, all other references to `wp-admin` in EDD core are to file inclusions, which can remain assuming `wp-admin`. The only one that is a problem with users like this is the one for sessions and assuming the AJAX URL.

I vote that we make a similar function to `edd_doing_cron()`:
```
function edd_doing_cron() {

	// Bail if not doing WordPress cron (>4.8.0)
	if ( function_exists( 'wp_doing_cron' ) && wp_doing_cron() ) {
		return true;

	// Bail if not doing WordPress cron (<4.8.0)
	} elseif ( defined( 'DOING_CRON' ) && ( true === DOING_CRON ) ) {
		return true;
	}

	// Default to false
	return false;
}

```

If we do this, we're abstracting and using the new functions available `wp_doing_cron()` which was added in WP 4.7, but since we support WP 4.4+ we need a backcompat method.

I will just point this out though that changing the `wp-admin` URL does nothing more than make plugins have a hard time with it. It adds no security layer other than security by obscurity and the admin URL can be easily acquired, in a few ways. While I don't think we should rewrite all associations of `wp-admin` as all but one are for file includes, we should use a detection of `wp_doing_ajax`

**Comment by cklosowski** [comment]
This is already done in EDD 3.0. We moved to using the `admin_url` function to do all this.
