### ISSUE TITLE
Edit discount screen: Add overview of related payments

### ISSUE THREAD

**Issue by flowdee** [awesomemotive/easy-digital-downloads#6431]
I often have the situation that I need to get an overview of customers/payments that used a specific discount code. Therefore it would be very handy if the edit discount screen provides such an information which shouldn't be a problem I assume.

Here's a quick scribble what I mean:

<img width="1562" alt="discount-codes-usage" src="https://user-images.githubusercontent.com/2278756/37449317-18641622-282a-11e8-873f-71da8f75abd9.png">

**Comment by cklosowski** [comment]
This could be something pretty handy. It will be easily implemented after EDD 3.0 is out with the new payments table and discount tables. I'll put it a bit after that.

**Comment by cklosowski** [comment]
With 3.0 we've made it so that you can click on 'View Orders' on a discount code's quick actions, and it will filter the orders list table to those that used the discount code.
<img width="290" alt="Screen Shot 2022-08-24 at 2 10 10 AM" src="https://user-images.githubusercontent.com/1390124/186379106-672bbb3a-1fdf-4cca-9c60-bfe443f2bd0d.png">
