### ISSUE TITLE
The EDD buy shortcode generates nonce that can be cached

### ISSUE THREAD

**Issue by sareiodata** [awesomemotive/easy-digital-downloads#7144]
### Expected behavior
When I do click on the buy button, with ajax enabled, I expect to get to the checkout with the product in my card. 

### Actual behavior
When I do that, I get to an empty cart page. 

### Steps to reproduce the behavior
1) Have caching enabled on the buy now button page. 
2) Have caching enabled for at least 24 hours without getting invalidated
3) The nonce in the button (that's generated with PHP) will become invalid after a while
4) Once you click the buy now button, the cart will be empty because the nonce is invalid.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch):  2.9.8

WordPress Version: 5.0.3 

Any other relevant information:
Using WP Rocket, but I don't think it's related to the actual caching plugin. 
The checkout page is not cached. I've tripple checked. 
Looking into the code, doing a simple link to the checkout with the product ID will probably solve this problem for me.

**Comment by cklosowski** [comment]
@sareiodata Thanks for the report. Are you using a shortcode to output the purchase link on a page, or just a the download-single.php auto generated purchase button?

**Comment by sareiodata** [comment]
The shortcode.

**Comment by webaware** [comment]
I'm seeing this behaviour also. There is a nonce that is added to / required by the Ajax action for add to cart. If Ajax is enabled then `edd_get_purchase_link()` creates a link with a nonce, and `edd_ajax_add_to_cart()` enforces the nonce.

The nonce, of course, breaks any cached pages when the nonce expires, and that includes single product pages and taxonomy pages.

I discovered this while investigating a problem on my shop. Very occasionally, all Buy Now buttons failed on all pages for anonymous visitors. Clearing the cache fixed it. It transpires that it happens when I haven't been doing much on the shop an thus the cache wasn't being refreshed as regularly, hence the problem with the nonce.

Why is the nonce required for the add to cart Ajax action? It isn't required for a regular form post adding to the cart.

For reference, I'm using WP Super Cache in "Expert" mode with nginx serving up cached pages, cache expiry of 604800 seconds (7 days), although I would expect this behaviour to exhibit with any page cache with cache expiry longer than the nonce expiry.

**Comment by cklosowski** [comment]
We've moved away from 'nonces' for add to cart in favor of an internal tokenizer in #8714
