### ISSUE TITLE
Download links unexpectedly producing "You do not have permission to download this file" error

### ISSUE THREAD

**Issue by danielbachhuber** [awesomemotive/easy-digital-downloads#8917]
Since updating to 2.11.2, at least some of our download links are producing a "You do not have permission to download this file" error.

I tracked this down to `edd_validate_url_token()` returning false when it should return true. I'm not sure why that's the case though, and don't know how to debug further ☹️ 

Here's an example URL:

```
https://www.wptasty.com/index.php?eddfile=167710%3A10%3A1%3A1&ttl=1634051586&beta=1&file=1&token=4b5cffaee74944c9903a20a7cab2d38737fac9bc2f04dbd4c0318dffafef1034
```

Notably, we're adding `beta=1` to the URL with the `edd_get_download_file_url_args` filter:

```php
/**
 * Filters the arguments used in a download link.
 *
 * @param array   $args       Existing query args.
 * @param integer $payment_id ID for the payment.
 * @param array   $params     Original parameters.
 * @return array
 */
public static function filter_edd_get_download_file_url_args( $args, $payment_id, $params ) {
	if ( ! empty( $params['download_id'] )
		&& WPT_EDD_TASTY_RECIPES_ID === (int) $params['download_id'] ) {
		$args['beta'] = 1;
	}
	return $args;
}
```

I also previously added `beta` as an allowed token:

```php
/**
 * Parameters allowed in signed URLs.
 *
 * @param array $args Existing parameters.
 * @return array
 */
public static function filter_edd_url_token_allowed_params( $args ) {
	$args[] = 'beta';
	return $args;
}
```

Maybe related to #8852? My hacky temporary fix is `add_filter( 'edd_validate_url_token', '__return_true' );`.

**Comment by danielbachhuber** [comment]
> The reason for forcing a specific order on the parameters was due to issues with some caching options/hosting configurations:

Er, right. But you could always sort the parameters alphabetically when generating the token, such that the order in the URL wouldn't matter.

> I don't love the short term fix I suggested--because it's not a good long term fix--but it should fix the issue for all of your links.

The other fix we can consider is that I remove the `beta` parameter entirely. It's lingering from a past test.

In other words, if we're the only ones that were bitten by this, maybe you don't need to spend a lot of effort trying to solve it.

**Comment by sergeykomlev** [comment]
I found that this issue occurs in my system because of the following line and not because of query string order.

https://github.com/awesomemotive/easy-digital-downloads/blob/0c0bcd9579ca8b150196509c22d07b6c13bb84a3/includes/process-download.php#L854

Looks like my system remove `:` symbol from `eddfile` string when the function `parse_url` is used with an empty array as the function argument.

So instead of `111111:22222:3:4` it's converted to `1111112222234` and this breaks all of my download links because tokens going to be different. I think this issue coming from Cloudflare, Redis, cache, or something like that.

Solution is add `$args` to function `parse_url`.

```php
$parts = parse_url( add_query_arg( $args ) );
```
