### ISSUE TITLE
3.0 - Re-add download category and tags to admin sub navigation

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9003]
### Expected behavior
I expect to be able to edit categories and tags on the "Downloads" post type screen.

### Actual behavior
No navigation bar exists in current 3.0 branch.

**Comment by robincornett** [comment]
It looks like that's due to a change we made in 2.11.3, where we opted not to output the tags due to reverting to using standard WP `h1` elements instead ([ref](https://github.com/awesomemotive/easy-digital-downloads/blob/release/3.0/includes/admin/admin-actions.php#L47)), but we do need to put it back in 3.0 somehow. Adding it back without changes results in this:

![image](https://user-images.githubusercontent.com/4853066/143306931-f987b0e2-0023-4aa7-b5f0-ccc32b30d515.png)
