### ISSUE TITLE
3.0 - Refunds trigger "edd_after_payment_actions" hook

### ISSUE THREAD

**Issue by ashleyfae** [awesomemotive/easy-digital-downloads#9031]
### Expected behavior
When I process a refund, I do not expect the `edd_after_payment_actions` hook to fire.

### Actual behavior
The hook does fire.

### Steps to reproduce the behavior
1) Hook into `edd_after_payment_actions` and do something (just log something or whatever).
2) Refund an order.
3) Note that the `edd_after_payment_actions` action is triggered.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch):

WordPress Version:

Any other relevant information:

Other things to note, but not confirmed:

- I assume this code is also running on the refund object: `edd_increase_earnings( $item->product_id, $item->total );` . I believe the order earnings are meant to be **gross** -- not **net**. Because this is running, it's incorrectly decreasing the download earnings (presumably).

**Comment by cklosowski** [comment]
There are some challenges with not running this for `after_payment_actions`. The purpose of that hook is to allow for running 'non-critical' actions on a payment after it has transitioned status. For instance sending API calls to external services that are not critical to the order being completed, like adding to a list or sending a push notification.

I think it would be expected that this same type of hook runs for refunds, so maybe the issue is that we're doing some things here that we maybe hsouldn't, or this could be related to #9087  @robincornett ?
