### ISSUE TITLE
Software Licensing Multisite

### ISSUE THREAD

**Issue by digamber89** [awesomemotive/easy-digital-downloads#9073]
### Explain your enhancement (please be detailed)
Currently, EDD Software Licensing Updater does not work if the plugin is only activated in a sub-site instead of main site.
There are solutions to add must use plugin for updaters - but - this is a hassle for the customers.
Is there really no way to get / check for updates ?

### Justification or use case
Customers should not need to add another plugin for updates.

**Comment by cklosowski** [comment]
Since development of the Software Licensing updater class is managed elsewhere and we've recently made changes to improve this so it's working in a more expected manor I'm closing this.

If you have further issues with this please reach out to our support team and submit a ticket so we can debug it further.
