### ISSUE TITLE
3.0 - Refunds - Partially refunded status ignores free products, setting original order to refunded.

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#9079]
### Expected behavior
When an order contains a mixture of free and paid products. Refunding only the paid products, should set the original order to 'partially refunded'. Refunding all products on the order should set the original order to 'refunded'.

### Actual behavior
If I have 1 paid product and one free product on an order, and I refund only the paid product, the original order is marked as 'refunded'. This could have negative consequences on things like license keys for free products, as a refunded order disables all license keys.

### Steps to reproduce the behavior
1) Make a purchase with 1 free and 1 paid product
2) Refund the paid product
3) Verify the original payment is 'refunded' instead of 'partially refunded'

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:

**Comment by robincornett** [comment]
I think part of the issue here is that we are not allowing "refunds" for free items (or free orders) at all. So I guess one question is whether we should change that behavior and allow refunds on free items? I'm thinking the quantity changes we are making for #8281 could help us here--instead of just [comparing totals for the refund status](https://github.com/awesomemotive/easy-digital-downloads/blob/release/3.0/includes/orders/functions/refunds.php#L385-L393), we can compare quantities?

**Comment by cklosowski** [comment]
@robincornett I don't think we need to allow refunds on the free items, but the order's value shouldn't be used to determine the 'refunded' status entirely. We should add a check to see if we've refunded both the full quantity, AND the full amount before marking something as fully refunded.
