### ISSUE TITLE
3.0 - Downloads Sales/Earnings numbers are not consistent

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9087]
### Expected behavior
I expect the sales/earnings numbers for a download to be accurate.

### Actual behavior
Depending on what actions were taken most recently, the numbers can be very different.

### Steps to reproduce the behavior
Not really steps to reproduce the behavior, but noting the different times and places and ways this data is calculated:
1. When an order is created, the sales and earnings numbers are increased.
    - The number of _sales_ here is actually the _quantity_ of an item purchased.
    - The _earnings_ factor in the quantity as well.
 2. Based on the work done for #8659, a philosophical change was made for the Download Recount Stats tool. With that tool, recounting the stats for a download:
     - For _sales_, the number of times the download was sold is what's counted. Quantity is ignored.
     - For _earnings_, the sum of all totals for that download is used. So quantities are included.
     - Based on that same PR, only sales are included, not refunds.
3. For #9080, it was noted that refunds are being included in the download reports, which is skewing those numbers. The open PR uses the same logic as the recount stats.

With all this in mind, you can end up with wildly different numbers based on what's happened most recently, especially when refunds are involved. Fixing the open refunds issues (also #9031 which I haven't mentioned yet) will alleviate some of these, but it is still possible to end up with reports which show different numbers (based on a direct DB query) than what a download will show (based on incremental updates).

As an example, I have a download which is $47.
- I recounted the stats and the download shows 9 sales, $893 in earnings (one order had a quantity of 2 and one had a quantity of 10).
- I checked out the issue/9085 branch so I could create a manual order without stats being duplicated and created one order with a quantity of 10 for that download. The new stats show 19 sales and $1363 in earnings. Note that the Reports > Downloads numbers here will be inconsistent with what shows for the download elsewhere.
- I run the recount tool again and the sales are now 10 and $1363.

### Information (if a specific version is affected):
PHP Version: 7.4
EDD Version (or branch): various 3.0 branches
WordPress Version: 5.9

Any other relevant information:
My gut inclination is that we really need to add a `recalculate_stats` method to the download class and use that instead of the increase/decrease methods. With the order items and orders tables, that's actually fairly straightforward to implement and would make significant strides to make the numbers throughout EDD consistent. We did this for the customer purchase count and value data in #7947; making this change for downloads would be consistent with that.

One question, though, is what numbers are expected and what are correct?
- Is the number of sales of a download really the number of _times_ it was sold, or is it the overall quantity sold of that download?
- Should download earnings/sales change when an order is refunded? Meaning, which is correct, the current behavior (decreasing sales/earnings) or the recount tool? Note that part of refactoring the recount tool included changing the label for earnings to be "Gross Revenue" to clarify this, but it did introduce a disconnect.

**Comment by cklosowski** [comment]
For historical reference, the 'ledger' functions for 'increase/decrease' were created due to the fact that running a full recalculation on the stats after each action that modified them would be overwhelmingly non-performant. 

With that in mind, I would urge us to still make use of DRY methodology and instead of a `recalculate_stats` we make separate methods for recalculating both earnings and sales.

## So what are earnings and sales counted as?
Sales should be based on quantity, not number of orders. It is a unit, not a cumulative number of orders that contain the product.

## So do we want Gross or Net?
Ultimately we want to provide store owners with the best picture of what their product(s) performance is. That means we really need to be providing them with both Net and Gross values, for both Sales (units) and earnings (revenue).

At a glance, we should be showing the store owner the most accurate representation of their 'take home' earnings, which would be Net. With that being said, we should also make it easy for them to see their 'gross' earnings. This would make it possible for a store owner to identify problematic products that produce a higher % of refunds, due to the Gross/Net calculations being higher.

## My choice on the matter
The current 'stats' for a download, and for the store in general should be Net. If I'm a business owner, and am looking at my daily report, I don't so much care about how much money I process, I care more about how much money is going to make it to my bank. Because of this we should use the existing 'default' display of a products sales and earnings as Net. We can then register an additional stat for each product as a 'Gross' stat, that we can use not only in calculations but also for comparison.

## What needs to happen then?
We should update anywhere we are altering the stored value of a products stats to update both the existing values as net, and in addition create a gross value for sales and earnings. These recalculate methods should exist in the product level itself and also be made part of the recalculate stats tool.

Questions on that @robincornett?

**Comment by robincornett** [comment]
That sounds more or less like what I was thinking. I think having both net and gross available is helpful and we can work to reduce duplication.
