### ISSUE TITLE
3.0 - Chart dates are showing incorrect dates and data for date ranges

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9223]
### Expected behavior

I expect to see the correct date on the graph, instead I see tomorrow (it's the 8th today):

<img width="1083" alt="Screenshot 2022-06-08 at 17 46 04" src="https://user-images.githubusercontent.com/22668877/172646634-4c79a4d9-145e-43aa-9adf-f893eabb94c2.png">

### Actual behavior
It's showing a day in advance on the graph. At first I thought this was an issue with timezones, but even if it was it wouldn't cause an issue as my timezone is GMT which closely matches UTC. Also within the database, the dates are all for the 8th (not the 9th).

**Comment by davidsherlock** [comment]
This seems to be specifically for "this week", "this month", etc.

**Comment by cklosowski** [comment]
The actual cause was due to the way we were collecting dates for output on the graph. We ended up having to have 2 date arrays.
1. The first in UTC to collect the adjusted local time into UTC for the database query (so we're always querying in UTC)
2. The 2nd is an array of the local timezones for use to display the chart.

**Comment by davidsherlock** [comment]
Good find @cklosowski! I didn't get a chance to dig deep into this one.

**Comment by cklosowski** [comment]
No worries @davidsherlock, it was a heck of an issue to sift through. 3.0 has a library change moving away from Flot to Chart.JS so there is always a little learning to do about the different libraries :)
