### ISSUE TITLE
3.0 - Free Purchases show Payment Method as "Store Gateway" in e-mail receipts

### ISSUE THREAD

**Issue by ejoflo** [awesomemotive/easy-digital-downloads#9317]
### Expected behavior
When a user/buyer checks out on a live production site and purchases an item that is $0.00, the Payment Method reported to them via Purchase Receipt and/or Sales Notification should say "Free Purchase". This behavior was default for EDD 2.0.

### Actual behavior
On a live production site, when a user makes a purchase that is essentially free $0.00, the Payment Method that is reported in both the Purchase Receipt and Sales Notification templates under {payment_method} is now Store Gateway.

### Steps to reproduce the behavior
1) Add a download/item that is $0.00
2) Place store in live mode
3) Purchase said item

### Information (if a specific version is affected):
PHP Version: N/A

EDD Version (or branch): 3.0.1

WordPress Version: 5.9.3

**Comment by cklosowski** [comment]
This is not a bug as is the intended behavior. Since there are a number of reasons that an item might be $0, we chose to make any purchase that is not processed through an external part of the Store Gateway so that it could have proper reporting and statistics run on it. Prior to this, there was no 'gateway' for orders of this type.

Many things changed in EDD 3.0 in order to facilitate reporting and accuracy. This was one of them.
