### ISSUE TITLE
Toggle button to "Automatically calculate amounts" not working in Safari

### ISSUE THREAD

**Issue by zkawesome** [awesomemotive/easy-digital-downloads#9331]
### Expected behavior
When I am adding a new Download into the Order, I expect the toggle button `Automatically calculate amounts` to show a form below it.

### Actual behavior
Toggling the button is not showing the form and there is an error thrown to the console.

### Steps to reproduce the behavior
1) Create new order
2) Click to `Add download`
3) Toggle `Automatically calculate amounts`

Browser: **SAFARI** !

**Comment by cklosowski** [comment]
I've been play around with this and here are a few things I've looked at (which haven't fixed it)

1. I thought maybe the fact that the input is wrapped in the `label` element might be triggering the `Type Error` message in console, since clicking the label and also clicking the 'checkbox' might cause a 'double' click event and it caught the label, but that is not it.
2. I tried adding a 'value' attribute to the input thinking maybe that it was a type error in determining the value, but that is not it.
3. I've looked at trying to console.log within the `onAutoCalculateToggle` function but that is not logging, and it Type Errors before that.

Based on all that, it seems that the binding of the event here is the problem possibly:
```
		// Delegate additional events.
		this.addEvents( {
			'change #download': 'onChangeDownload',
			'change #quantity': 'onChangeQuantity',
			'change #auto-calculate': 'onAutoCalculateToggle', <---------- Here

			'keyup #amount': 'onChangeAmount',
			'keyup #tax': 'onChangeTax',
			'keyup #subtotal': 'onChangeSubtotal',

			'click #set-address': 'onSetAddress',

			'submit form': 'onAdd',
		} );
```

**Comment by cklosowski** [comment]
After some more digging, I'm finding the issue is here in the compiled scripts:
```
if((void 0===u()(n)||9!==n)&&e.selectionStart)
```

If I manually modify this compiled script to `return false` right before this `if` statement, it works fine. So it appears the event registration is causing a problem in backbone with Safari?

**Comment by cklosowski** [comment]
Correction, the issue is in our `base.js` class in the `	onChange( e ) {` function. Digging into that now.
