### ISSUE TITLE
Individual Download report does not show data in the sales tile

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9337]
### Expected behavior
Filtering by individual downloads to show me the actual sales data

### Actual behavior
Amounts stay at 0

### Steps to reproduce the behavior
1) Go to Downloads > Reports and filter by any specific Download
2) The Sales tile is 0 https://a.supportally.com/68BZbZ

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): main

WordPress Version: latest

Any other relevant information:
This was reported on .org but the screenshot above is from my local https://wordpress.org/support/topic/new-v3-0-reports/

**Comment by robincornett** [comment]
Looking into this and tiles in general today and I'm seeing a few issues:
- The `download_sales_earnings` endpoint needs to be updated to account for single price products. Right now it's casting all price IDs to an integer and that will return no results if there isn't a price ID. See the `edd_register_downloads_report` for this.
- Not specific to this tile, but if a `revenue_type` is passed to the `get_order_count` method in the stats class, it's ignored and the tiles use whatever was set up when the class was instantiated. So the `overview_sales` endpoint is setting a `revenue_type` of net, but `gross` is actually what's being used because that's the default.
- In the reporting functions, there are a mix of ways that the stats class is instantiated. Sometimes it's instantiated with the parameters that are meant to be used in the query; sometimes it's instantiated with no parameters and they're set in the query instead, and (as in the case of the order count) the parameters there may or may not be properly accounted for.

I think all of the tiles need to be reviewed, and the order of operations in the stats class as well.
