### ISSUE TITLE
Add Adjustment input fields cause weird cursor behavior

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9357]
Replicating this could be tricky but it has been reported by several customers and I believe @spencerfinnell saw it too or perhaps he mentioned something about it in Slack (can't find it now).

It is happening to both the amount and description fields. Here is a small GIF just now on my local on the 3.0.3 branch https://a.supportally.com/oCTXWx
MacOS 12.5 with Firefox 103.0.2 for me.

This is what @spencerfinnell mentioned in Slack when I posted this first: 
 there is (attempted) handling of focus/caret position here: https://github.com/awesomemotive/easy-digital-downloads/blob/main/assets/js/admin/orders/order-overview/views/base.js

**Comment by mihaijoldis** [comment]
Just wanted to ping on this one again as it is really annoying.

**Comment by spencerfinnell** [comment]
@mihaijoldis Try #9439, which should fix it in Firefox, and continue working as expected in Safari in Chrome. The one remaining oddity is using the up/down buttons within `number` fields. That puts the caret position back at the start, but isn't as much of an issue because you're already using the mouse.

Sorry, I meant to look at this sooner.

**Comment by mihaijoldis** [comment]
@spencerfinnell YES THANK YOU! Works perfectly now!
