### ISSUE TITLE
Purchase receipt order items is limited to 30 results

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9379]
### Expected behavior
If I purchase more than 30 items in a single order I would expect to be able to see them all on the receipt page

### Actual behavior
Only 30 items are being returned in the Download List.

### Steps to reproduce the behavior
1) Purchase more than 30 items in a single order
2) View the receipt page.

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): main

WordPress Version: latest

Any other relevant information:
The issue has been reported by a customer here https://secure.helpscout.net/conversation/1985126872/2121575?folderId=5747299

**Comment by cklosowski** [comment]
The root cause of this is that `Order->get_items()` is [calling the order items table](https://github.com/awesomemotive/easy-digital-downloads/blob/release/3.0.3/includes/orders/classes/class-order.php#L345), without specifying the number of items to get, which [sets us into the default](https://github.com/awesomemotive/easy-digital-downloads/blob/release/3.0.3/includes/orders/functions/items.php#L172) of `30`

**Comment by cklosowski** [comment]
I think we could probably get away with setting a reasonable  default here within `Order->get_items()`, by setting it to something like `200`. This would ensure that we won't cap out unless in an even more extreme case.
