### ISSUE TITLE
First Download in Bundles Not Being Added to Customer Account

### ISSUE THREAD

**Issue by WildeWebMarketing** [awesomemotive/easy-digital-downloads#9517]
## Bug Report

When a customer purchases a bundled product, the very first download in the bundle does not get added to the customer's account.

Must regenerate license keys to fix the problem, every time.

Please note, these bundled products were created in January of 2021 and only recently started to exhibit this behavior.

**Comment by mihaijoldis** [comment]
Hey @WildeWebMarketing 

Could you please edit the Download that is a bundle in EDD and then simply click the Update button for it? Don't make any changes just update so that the data refreshes in the database. Once you do that you can regenerate the missing license keys for the order in question.

Once you save the download again try placing a test purchase and see if that fixed the issue, please.

**Comment by WildeWebMarketing** [comment]
Thank you @mihaijoldis!

I had to go through and resave all the bundles, but it seems to solve the issue. Any idea what changed recently that would have caused this?

Thank you again for your response. I appreciate it.

**Comment by robincornett** [comment]
There was a bug for variably priced bundles which resulted in the price assignments for each bundled product being incorrectly saved when the bundle was updated. That was fixed, but if the price assignments were out of sync then the bundle could miss a file as you experienced. Confirming the bundled products and saving the download is the most reliable fix.
