### ISSUE TITLE
Discount code amount is shown but total shows non-discount price so transaction fails

### ISSUE THREAD

**Issue by WildeWebMarketing** [awesomemotive/easy-digital-downloads#9594]
## Bug Report
When discount code is used, order shows discount code and amount, but total still shows non-discounted amount.

This causes transaction to fail because amount customer paid is different than incorrect order amount.

UPDATE: I've gone through everything I can think of and the only thing that I can find that would affect the payment is the following function that I use. The function checks to see if the user has already received a freebie item and, if not, adds the item to their order. The item is free, but is it recalculating the total and not taking possible discounts into consideration? If this is the problem, how do I fix this?

`function add_chained_product($payment_id, $data){`
`  $payment = new EDD_Payment($payment_id);`
`  $customer = new EDD_Customer( $payment->user_info['email'] );`
`  $user_id = $payment->user_info['id'];`
`  if($user_id == 0 && $customer->user_id !== 0){`
`      $user_id = $customer->user_id;`
`  }`
`  if(!edd_has_user_purchased($user_id, 100)){`
`    $payment->add_download( 100 );`
`  }`
`  $payment->save();`
`}`
`add_action( 'edd_insert_payment', 'add_chained_product', 100, 2 );`

**Comment by WildeWebMarketing** [comment]
This is literally ruining my day. Any guidance and I will do a summersault...or at least make an attempt. :) Anyone deal with anything like this before?

**Comment by robincornett** [comment]
If download ID 100 is not a free product, adding it to the `$payment` object without adjusting the price will result in what you're seeing, because EDD retrieves the product price from the download. You can override it by using the second parameter for `add_download`. [We have an example of adding a product with a `0` price in our tests](https://github.com/awesomemotive/easy-digital-downloads/blob/main/tests/orders/tests-edd-payment.php#L140-L157) which should be helpful. The [default arguments for that parameter can be found in the add_download method](https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/payments/class-edd-payment.php#L1023-L1032) in the payment class.

The best way to receive support for EDD in the future is to [contact our team](https://easydigitaldownloads.com/support/) please.

**Comment by WildeWebMarketing** [comment]
This is still an issue, whether or not the product is free.

To reproduce:

1. Install EDD

2. Create dummy product (Awesome Product) for $9.99 (price irrelevant)

3. Create dummy product (Free Product) for $0.00 (again, price irrelevant)

4. Create discount code for 40% off (Code: BLACK)

5. Add the following to functions.php (changing product IDs to Free Product ID :

```
function add_chained_product($payment_id, $data){
  $payment = new EDD_Payment($payment_id);
  $customer = new EDD_Customer( $payment->user_info['email'] );
  //error_log(print_r($payment->total, true));

  $user_id = $payment->user_info['id'];
  if($user_id == 0 && $customer->user_id !== 0){
      $user_id = $customer->user_id;
  }
  if(!edd_has_user_purchased($user_id, 1334)){
    $payment->add_download( 1334 );
  }
  //error_log(print_r($payment->total, true));
  $payment->save();
}
add_action( 'edd_insert_payment', 'add_chained_product', 100, 2 );
```
6. Add Awesome Product $9.99 to Cart

7. Add discount code BLACK to order (discount will be reflected in order)

8. Complete Checkout

Now order will complete. Chained download is successfully added to order. But it you look at the order, the discount shows, but the total is incorrect, regardless if the product is free or not.

I added error_log(print_r($payment->total, true)); in two places in the function (currently commented out), which prints the total before and after the add_download into the error log. The first total is correct, the second is missing the discount.

I have also tested by adding $args and changing the price from 0.00 to 1.00, with the same result.
