### ISSUE TITLE
Reported issue moved with no comments

### ISSUE THREAD

**Issue by leewillis77** [awesomemotive/easy-digital-downloads#9634]
## Expected behaviour
When I report a bug I expect it to get reviewed, and either resolved or a response posting indicating the outcome of the bug report

## Actual behaviour
When I reported https://github.com/awesomemotive/easy-digital-downloads/issues/9618 it disappeared without any comment, so no idea what's happened to the issue, or whether it will be resolved or not...

**Comment by cklosowski** [comment]
Hi @leewillis77. I left a comment on the issue saying:
`Thanks @leewillis77 we will look into this behavior.`

The issue was transferred to a private repo where we are working and maintaining both the Free and Pro version of Easy Digital Downloads in a single build. We've reviewed it and have it in a milestone for version 3.1.1.5.

We're still working through some of the processes and procedures here to determine the best way to handle issues that we're managing within the private repo that affects both the build for Pro and Free, and exploring possible solutions with what GitHub has available for copying/transferring/duplicating issues without a lot of added overhead.

**Comment by leewillis77** [comment]
Hi Chris; 

Thanks for the reply. Unfortunately I never got that message, the issue just disappeared, which from my point of view is pretty unhelpful, so please do review that process for future issues, as what happened here definitely doesn't work from a contributor's point of view.

**Comment by robincornett** [comment]
@leewillis77 thanks for your patience; we did have to adjust the milestone for this issue, but it's been approved for the 3.1.3 release.
