### ISSUE TITLE
Double orders possibly related to Debug log -  get_order_from_capture_object() - Transaction ID mismatch. 

### ISSUE THREAD

**Issue by cartoonsmart** [awesomemotive/easy-digital-downloads#9642]
We've seen an uptick in double orders where it seems the buyer isn't being sent to the confirmation fast enough (which could be Paypal not processing things quick enough), and then make a duplicate order. These cases all seem to be related to a Debug log like this...

2023-4-22 14:17:39 - PayPal Commerce - Exiting webhook due to an exception. Message: get_order_from_capture_object() - Transaction ID mismatch. Expected: ; Actual: 46Y57056XV5049614

And one of the duplicate orders will be missing the Transaction ID. 

Any ideas what's happening?

**Comment by robincornett** [comment]
Hi @cartoonsmart, can you [contact our support team](https://easydigitaldownloads.com/support/) on this, please? They would be happy to work with you to see what's going on.

**Comment by cartoonsmart** [comment]
Thanks, I did already. Fine reply, but the standard "update to the latest version", and admittedly I was a couple minor updates behind, but checking the Debug logs on a few clients  I've seen that Transaction ID mismatch error date back for years (pre-EDD 3) but very sporadically. Again I think this is mainly human error due to impatience and an uptick of the behavior is related to Paypal not processing things quickly. I also think it's happening with buyers using the black payment button where they enter the Debit or Credit Card in the cart.

Anyway, just seeing if anyone had any ideas or thoughts on this. Feel free to close it if this is the wrong place. Thanks.

**Comment by cartoonsmart** [comment]
This is still happening and I even downgraded a client back to Paypal Standard thinking that would resolve it. What is strange is the Transaction ID is missing in the Order Extras panel, but I do see it in the Store Bot notes. Plugin's are all up to date.

**Comment by cartoonsmart** [comment]
Gonna close this (thanks for listening). This could have been an issue with some post-purchase code we run. The site is on php8.1 and I noticed php fails trying to add what it thought was two strings instead of numbers (worked fine in php 7.whatever). Anyway, I'm hoping thats it. Fingers crossed it's just a case of "keeping my own side of the street clean", so to speak. =)

**Comment by robincornett** [comment]
@cartoonsmart thank you for the update! If you have a chance and can share an example of the code you are running, or at least the part you think is causing the issue, I would appreciate it. We are tracking PHP 8/8.1 potential compatibility issues to work on in a future release.

At this time, WordPress Core still only officially supports PHP 7.4 at the highest; 8+ are considered in beta support, just because there is a lot of code to review. We are working to be ready to be compatible as well, but some things we will need to change do require significant revision.

Thanks again for the update and any additional information you can share.
