### ISSUE TITLE
Manual Purchase and Payement GateWay

### ISSUE THREAD

**Issue by X-Raym** [awesomemotive/easy-digital-downloads#9645]
### Expected behavior

For Manual Purchase page:

- hiding payement gateways set as inactive

![Here what I see](https://i.imgur.com/WyYrbRy.gif)

![Despite this setting](https://i.imgur.com/4CP6KsG.png)

- having manual gateway in payement

As you can see on screenshot above, manual gateway doesn't exist.

### Information (if a specific version is affected):

EDD Version (or branch): 3.1.1.3

Thx!

**Comment by X-Raym** [comment]
Oh maybe the full list on edit page is for being abel to chose with non public gateway ?
Anyway, Manual would be nice by default

the custom code posted here https://pippinsplugins.com/create-custom-payment-gateway-for-easy-digital-downloads/ has issues ( =&gt; is displayed instead of => )

**Comment by robincornett** [comment]
Hi @X-Raym thanks for the report. You are correct; it is intentional to show all gateways when manually adding an order. A store may need to keep a gateway set up for subscription payments, for example, but not have it enabled for new orders. And most stores will not want to have the Store Gateway enabled for front end purchasing.

When I go to manually add a new order, the manual gateway is selected for me by default, but the list of gateways is just shown in the order that they are registered to the site.

I'll make a note to ask our team to make sure we have an up to date snippet for registering custom gateways; thank you!

**Comment by X-Raym** [comment]
@robincornett Thx for explaination!
There was no manual gateway as you can see in my screenshot above.
I manually added thx to code snipper but having it built-in would be nice 😉
Cheers !
